language: python

sudo: required

services:
- docker
- privileged: true

python:
- 2.7
- 3.5
- 3.6
- nightly

before_install:
- docker build -t simtool . 
- docker run --privileged --rm=false -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w $PWD simtool ./sim/tests

install:
- pip install coveralls pytest pytest-runner
- pip install ./sim

script:
- cd ./sim
- coverage run --source boutiques setup.py pytest

after_success:
- coveralls

deploy:

